### ISSUE TITLE
Ascii error

### ISSUE THREAD

**Issue by simon-bueler** [c3r34lk1ll3r/tmux-networkmanager#2]
I get this error when running the script:

```
Traceback (most recent call last):
  File "nmcli.py", line 76, in <module>
    show_menu();
  File "nmcli.py", line 10, in show_menu
    datas=datas.decode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1317: ordinal not in range(128)
```

Can you imagine how to fix this?

**Comment by simon-bueler** [comment]
Changing
https://github.com/c3r34lk1ll3r/tmux-networkmanager/blob/f887f47182a843a36c0a6c9b048250ff8a5c7826/scripts/nmcli.py#L10
to
`datas=datas.decode('UTF-8')`
Fixed the issue.

**Comment by c3r34lk1ll3r** [comment]
Thanks for reporting this issue. 

Fixed as you suggested.
